[package]
name = "aws-sdk-retrieve-required"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
csv = "1.3.0"
rayon = "1.10.0"
reqwest = {  version = "0.12.3", features = ["blocking"] }
scraper = "0.19.0"
serde = { version = "1.0.197", features = ["derive"] }
